apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ride-hailing-staging
namePrefix: staging-
resources:
  - ../../base
  - secrets.yaml
configMapGenerator:
  - name: gateway-config
    envs:
      - config.env
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ride-hailing/gateway
    newTag: staging
patchesStrategicMerge:
  - patch.yaml
