apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ride-hailing-prod
namePrefix: prod-
resources:
  - ../../base
  - secrets.yaml
configMapGenerator:
  - name: user-config
    envs:
      - config.env
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ride-hailing/user
    newTag: prod
patchesStrategicMerge:
  - patch.yaml
