services:
  gateway:
    container_name: service-gateway
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_HTTP_ADDR=:8080
      - GATEWAY_AUTH_ENABLED=false
    mem_limit: 256m
    cpus: "0.50"
    depends_on:
      - nats
      - postgres
      - redis

  ride:
    container_name: service-ride
    build:
      context: .
      dockerfile: services/ride/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - RIDE_GRPC_ADDR=:50051
      - RIDE_POSTGRES_DSN=postgres://ride:ride@postgres:5432/rides?sslmode=disable
      - RIDE_NATS_URL=nats://nats:4222
      - RIDE_OUTBOX_ENABLED=true
    mem_limit: 256m
    cpus: "0.50"
    depends_on:
      - postgres
      - nats

  nats:
    container_name: nats
    image: nats:2.10
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    mem_limit: 128m
    cpus: "0.25"

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=ride
      - POSTGRES_PASSWORD=ride
      - POSTGRES_DB=rides
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ride -d rides"]
      interval: 5s
      timeout: 3s
      retries: 10
    mem_limit: 512m
    cpus: "1.0"

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    mem_limit: 128m
    cpus: "0.25"

  migrate:
    image: kukymbr/goose-docker
    container_name: migrate
    restart: "no"
    mem_limit: 256m
    cpus: "0.25"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgresql://ride:ride@postgres:5432/rides?sslmode=disable
    volumes:
      - ./services/ride/migrations:/migrations
