apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: user-config
    envs:
      - config.env
secretGenerator:
  - name: user-secrets
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ride-hailing/user
    newTag: staging
