apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  labels:
    app: notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
        - name: notify
          image: ride-hailing/notify:latest
          ports:
            - containerPort: 8090
              name: http
          envFrom:
            - configMapRef:
                name: notify-config
            - secretRef:
                name: notify-secrets
