apiVersion: sealedsecrets.bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: matching-secrets
spec:
  encryptedData:
    PLACEHOLDER: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: matching-secrets
