apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride
  template:
    metadata:
      labels:
        app: ride
    spec:
      containers:
        - name: ride
          image: ghcr.io/daffahilmyf/ride-hailing-ride:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          env:
            - name: RIDE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: ride-db
                  key: dsn
            - name: RIDE_INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ride-secrets
                  key: internal_auth_token
            - name: RIDE_NATS_URL
              valueFrom:
                secretKeyRef:
                  name: ride-secrets
                  key: nats_url
          volumeMounts:
            - name: config
              mountPath: /config
          args: ["serve", "--config", "/config/config.yaml"]
      volumes:
        - name: config
          configMap:
            name: ride-config
