apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: ghcr.io/daffahilmyf/ride-hailing-location:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50053
          env:
            - name: LOCATION_INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: location-secrets
                  key: internal_auth_token
            - name: LOCATION_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: location-secrets
                  key: redis_password
            - name: LOCATION_NATS_URL
              valueFrom:
                secretKeyRef:
                  name: location-secrets
                  key: nats_url
          volumeMounts:
            - name: config
              mountPath: /config
          args: ["serve", "--config", "/config/config.yaml"]
      volumes:
        - name: config
          configMap:
            name: location-config
