apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - name: matching
          image: ghcr.io/daffahilmyf/ride-hailing-matching:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
          env:
            - name: MATCHING_INTERNAL_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: matching-secrets
                  key: internal_auth_token
            - name: MATCHING_RIDE_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: matching-secrets
                  key: ride_internal_token
            - name: MATCHING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matching-secrets
                  key: redis_password
            - name: MATCHING_NATS_URL
              valueFrom:
                secretKeyRef:
                  name: matching-secrets
                  key: nats_url
          volumeMounts:
            - name: config
              mountPath: /config
          args: ["serve", "--config", "/config/config.yaml"]
      volumes:
        - name: config
          configMap:
            name: matching-config
